// swift-tools-version:5.9
// This file is generated by products/sdk-ios/release/build_spm_release.sh
// Do not edit by hand. Edit the template at
// products/sdk-ios/release/templates/Package.swift.tmpl instead.
//
// Layout (12 binary targets total, surfaced as 4 library products):
//
//   Shared (byte-identical across all variants -- shipped once):
//     util_ios_Shared, wbxaecodec_Shared, wbxaudioengine_Shared, mediastores_ios_Shared
//
//   Variant-specific (WebexSDK + UCFBridge are recompiled per variant):
//     WebexSDK_Full,    UCFBridge_Full
//     WebexSDK_Meeting, UCFBridge_Meeting
//     WebexSDK_Wxc,     UCFBridge_Wxc
//     WebexSDK_Message, UCFBridge_Message
//
// Each library product links the 4 shared targets plus the 2 variant-specific
// targets for its flavour, so consumers still get `import WebexSDK` regardless
// of which library product they depend on.
//
// The dedup is safe only as long as the 4 "Shared" frameworks remain
// byte-identical across all 4 variants. build_spm_release.sh verifies this
// invariant at packaging time and refuses to dedup on divergence.

import PackageDescription

let version = "3.16.3"
let base = "https://github.com/balaobulreddy/iOS-spm-test/releases/download/\(version)"

let package = Package(
    name: "WebexSDK",
    platforms: [.iOS(.v15)],
    products: [
        .library(
            name: "WebexSDK",
            targets: [
                "WebexSDK_Full",
                "UCFBridge_Full",
                "util_ios_Shared",
                "wbxaecodec_Shared",
                "wbxaudioengine_Shared",
                "mediastores_ios_Shared",
            ]
        ),
        .library(
            name: "WebexSDKMeeting",
            targets: [
                "WebexSDK_Meeting",
                "UCFBridge_Meeting",
                "util_ios_Shared",
                "wbxaecodec_Shared",
                "wbxaudioengine_Shared",
                "mediastores_ios_Shared",
            ]
        ),
        .library(
            name: "WebexSDKWxc",
            targets: [
                "WebexSDK_Wxc",
                "UCFBridge_Wxc",
                "util_ios_Shared",
                "wbxaecodec_Shared",
                "wbxaudioengine_Shared",
                "mediastores_ios_Shared",
            ]
        ),
        .library(
            name: "WebexSDKMessage",
            targets: [
                "WebexSDK_Message",
                "UCFBridge_Message",
                "util_ios_Shared",
                "wbxaecodec_Shared",
                "wbxaudioengine_Shared",
                "mediastores_ios_Shared",
            ]
        ),
    ],
    targets: [
        // ---------- Shared (one copy, referenced by every variant library) ----------
        .binaryTarget(
            name: "util_ios_Shared",
            url: "\(base)/WebexSDK-Shared-util_ios.xcframework.zip",
            checksum: "77b652c13a4a5714bafb51e44501fc0d18b9a32ec8c5e99f1add3ec8563554f8"
        ),
        .binaryTarget(
            name: "wbxaecodec_Shared",
            url: "\(base)/WebexSDK-Shared-wbxaecodec.xcframework.zip",
            checksum: "f2e54272b52dc9f5d834cf00ab485bcc174174cb9c2e130b8c33ce4de6559d18"
        ),
        .binaryTarget(
            name: "wbxaudioengine_Shared",
            url: "\(base)/WebexSDK-Shared-wbxaudioengine.xcframework.zip",
            checksum: "39f230f7112907805ea69f2889fd295bea0433c359c72621d4a0e704e805ccc5"
        ),
        .binaryTarget(
            name: "mediastores_ios_Shared",
            url: "\(base)/WebexSDK-Shared-mediastores_ios.xcframework.zip",
            checksum: "da4679cb030af023cdba7476d2eba9f0a03e86f39f967b0f250b9efd6010e182"
        ),

        // ---------- Full ----------
        .binaryTarget(
            name: "WebexSDK_Full",
            url: "\(base)/WebexSDK-Full-WebexSDK.xcframework.zip",
            checksum: "129470a0024ace1f78d0bf96641b68ffadf3f0fb4fd3db8473494629354761ec"
        ),
        .binaryTarget(
            name: "UCFBridge_Full",
            url: "\(base)/WebexSDK-Full-UCFBridge.xcframework.zip",
            checksum: "ff92f3463abc866836803f7861df0594145245f5ecd8091d3b53c5ede3478c38"
        ),

        // ---------- Meeting ----------
        .binaryTarget(
            name: "WebexSDK_Meeting",
            url: "\(base)/WebexSDK-Meeting-WebexSDK.xcframework.zip",
            checksum: "d1758bf1d8ae07d599789a7d523fa2f2a8d2c415e16ee95bae40da429f03e062"
        ),
        .binaryTarget(
            name: "UCFBridge_Meeting",
            url: "\(base)/WebexSDK-Meeting-UCFBridge.xcframework.zip",
            checksum: "9a24a99417b37274f621fa57d34794f8eeb7b53d853918686a245a1524c1b2c1"
        ),

        // ---------- Wxc ----------
        .binaryTarget(
            name: "WebexSDK_Wxc",
            url: "\(base)/WebexSDK-Wxc-WebexSDK.xcframework.zip",
            checksum: "7d7c5efd1bab5b2e99a42b66e78698fb96efd14efca5ea39719f8844066424a1"
        ),
        .binaryTarget(
            name: "UCFBridge_Wxc",
            url: "\(base)/WebexSDK-Wxc-UCFBridge.xcframework.zip",
            checksum: "681135fdc9a35760a6d885cebff9f01d5f87667bd26f0b2737351d9609c14b86"
        ),

        // ---------- Message ----------
        .binaryTarget(
            name: "WebexSDK_Message",
            url: "\(base)/WebexSDK-Message-WebexSDK.xcframework.zip",
            checksum: "4052cefcbf70604b02c588ede2446e111c4f138f68227256bd234f04dae5fa2c"
        ),
        .binaryTarget(
            name: "UCFBridge_Message",
            url: "\(base)/WebexSDK-Message-UCFBridge.xcframework.zip",
            checksum: "599ae7b6c864652942dc7aad8ac79865ec9692ec4f40363d49903fe1d4a65a42"
        ),
    ]
)
