// swift-tools-version:5.9
// This file is generated by products/sdk-ios/release/build_spm_release.sh
// Do not edit by hand. Edit the template at
// products/sdk-ios/release/templates/Package.swift.tmpl instead.
//
// Layout (13 binary targets total, surfaced as 5 library products):
//
//   Shared (byte-identical across all variants -- shipped once):
//     util_ios_Shared, wbxaecodec_Shared, wbxaudioengine_Shared, mediastores_ios_Shared
//
//   Variant-specific (WebexSDK + UCFBridge are recompiled per variant):
//     WebexSDK_Full,    UCFBridge_Full
//     WebexSDK_Meeting, UCFBridge_Meeting
//     WebexSDK_Wxc,     UCFBridge_Wxc
//     WebexSDK_Message, UCFBridge_Message
//
//   Broadcast (standalone, shipped once -- its own product):
//     WebexBroadcastExtensionKit
//
// Each WebexSDK* library product links the 4 shared targets plus the 2
// variant-specific targets for its flavour, so consumers still get
// `import WebexSDK` regardless of which library product they depend on.
//
// WebexBroadcastExtensionKit is a separate product (the SwiftPM equivalent of
// the WebexBroadcastExtensionKit CocoaPod). It only links system frameworks and
// communicates with the host app over a local socket, so it has no dependency
// on the WebexSDK frameworks. Add it to your Broadcast Upload Extension target,
// NOT to your main app target, and `import WebexBroadcastExtensionKit` there.
//
// The dedup is safe only as long as the 4 "Shared" frameworks and the broadcast
// framework remain byte-identical across all 4 variants. build_spm_release.sh
// verifies this invariant at packaging time and refuses to dedup on divergence.

import PackageDescription

let version = "3.16.4"
let base = "https://github.com/balaobulreddy/iOS-spm-test/releases/download/\(version)"

let package = Package(
    name: "WebexSDK",
    platforms: [.iOS(.v15)],
    products: [
        .library(
            name: "WebexSDK",
            targets: [
                "WebexSDK_Full",
                "UCFBridge_Full",
                "util_ios_Shared",
                "wbxaecodec_Shared",
                "wbxaudioengine_Shared",
                "mediastores_ios_Shared",
            ]
        ),
        .library(
            name: "WebexSDKMeeting",
            targets: [
                "WebexSDK_Meeting",
                "UCFBridge_Meeting",
                "util_ios_Shared",
                "wbxaecodec_Shared",
                "wbxaudioengine_Shared",
                "mediastores_ios_Shared",
            ]
        ),
        .library(
            name: "WebexSDKWxc",
            targets: [
                "WebexSDK_Wxc",
                "UCFBridge_Wxc",
                "util_ios_Shared",
                "wbxaecodec_Shared",
                "wbxaudioengine_Shared",
                "mediastores_ios_Shared",
            ]
        ),
        .library(
            name: "WebexSDKMessage",
            targets: [
                "WebexSDK_Message",
                "UCFBridge_Message",
                "util_ios_Shared",
                "wbxaecodec_Shared",
                "wbxaudioengine_Shared",
                "mediastores_ios_Shared",
            ]
        ),
        .library(
            name: "WebexBroadcastExtensionKit",
            targets: [
                "WebexBroadcastExtensionKit",
            ]
        ),
    ],
    targets: [
        // ---------- Shared (one copy, referenced by every variant library) ----------
        .binaryTarget(
            name: "util_ios_Shared",
            url: "\(base)/WebexSDK-Shared-util_ios.xcframework.zip",
            checksum: "c7b8fc3a5f4d0dd0e489bf1db14aea56b734680ca0c8c97e6a8daed69f3bad73"
        ),
        .binaryTarget(
            name: "wbxaecodec_Shared",
            url: "\(base)/WebexSDK-Shared-wbxaecodec.xcframework.zip",
            checksum: "fe23d02cf986d1f6b30f765de56a486986b32d5c363dd39d5b80a3832d86393a"
        ),
        .binaryTarget(
            name: "wbxaudioengine_Shared",
            url: "\(base)/WebexSDK-Shared-wbxaudioengine.xcframework.zip",
            checksum: "9b260113e5285da4e0dff39ecaf1d9e8966ee7a9df41a027afbf60f7d4f071f4"
        ),
        .binaryTarget(
            name: "mediastores_ios_Shared",
            url: "\(base)/WebexSDK-Shared-mediastores_ios.xcframework.zip",
            checksum: "997ac3e617646164b866a0f3e2754a1f3c2eeac70791d84abb9b1295fd0a9787"
        ),

        // ---------- Full ----------
        .binaryTarget(
            name: "WebexSDK_Full",
            url: "\(base)/WebexSDK-Full-WebexSDK.xcframework.zip",
            checksum: "674e4b32061227d975f86221667523dd81cc63035c995192eacf7d337012472c"
        ),
        .binaryTarget(
            name: "UCFBridge_Full",
            url: "\(base)/WebexSDK-Full-UCFBridge.xcframework.zip",
            checksum: "3b00900a102d58bc69f53d4bb42cbca704102fe3c44310045cdf5b1b0b0c6367"
        ),

        // ---------- Meeting ----------
        .binaryTarget(
            name: "WebexSDK_Meeting",
            url: "\(base)/WebexSDK-Meeting-WebexSDK.xcframework.zip",
            checksum: "544a5ccc278511e72484e8c1a1156855940fb4b4b64838cc62978cdc1707d0cf"
        ),
        .binaryTarget(
            name: "UCFBridge_Meeting",
            url: "\(base)/WebexSDK-Meeting-UCFBridge.xcframework.zip",
            checksum: "7f61f50709dfcca9310382206e21e0037a74926af8686c5322b1c3ff22b25388"
        ),

        // ---------- Wxc ----------
        .binaryTarget(
            name: "WebexSDK_Wxc",
            url: "\(base)/WebexSDK-Wxc-WebexSDK.xcframework.zip",
            checksum: "ed716342fda8f752b28131333d21701ddab9e91c7156c2e324aa28112438e8e4"
        ),
        .binaryTarget(
            name: "UCFBridge_Wxc",
            url: "\(base)/WebexSDK-Wxc-UCFBridge.xcframework.zip",
            checksum: "0d575cd01f839e5ef6a2cd4c3613266f6d8dbd8ec83e6d2e5a0914e87a1ed08e"
        ),

        // ---------- Message ----------
        .binaryTarget(
            name: "WebexSDK_Message",
            url: "\(base)/WebexSDK-Message-WebexSDK.xcframework.zip",
            checksum: "13fb33b07814b72b48a1a2ceac765631f8608f240aceacb94d2293e29bd185ec"
        ),
        .binaryTarget(
            name: "UCFBridge_Message",
            url: "\(base)/WebexSDK-Message-UCFBridge.xcframework.zip",
            checksum: "992ad4e9ce2550523dbbb923915719724cb71c4ac40c3b5fde9e0ec379ab59b5"
        ),

        // ---------- Broadcast (standalone product, shipped once) ----------
        .binaryTarget(
            name: "WebexBroadcastExtensionKit",
            url: "\(base)/WebexBroadcastExtensionKit.xcframework.zip",
            checksum: "9717d5b072897550ac40599ca79501ae42e2d0bb13e7d3a58e4b11d74ec027a8"
        ),
    ]
)
