// swift-tools-version:5.9
// This file is generated by build_spm_release.sh
// Do not edit by hand. Edit the template at
// templates/Package.swift.tmpl instead.
//
// Layout (13 binary targets total, surfaced as 5 library products):
//
//   Shared (byte-identical across all variants -- shipped once):
//     util_ios_Shared, wbxaecodec_Shared, wbxaudioengine_Shared, mediastores_ios_Shared
//
//   Variant-specific (WebexSDK + UCFBridge are recompiled per variant):
//     WebexSDK_Full,    UCFBridge_Full
//     WebexSDK_Meeting, UCFBridge_Meeting
//     WebexSDK_Wxc,     UCFBridge_Wxc
//     WebexSDK_Message, UCFBridge_Message
//
//   Broadcast (standalone, shipped once -- its own product):
//     WebexBroadcastExtensionKit
//
// Each WebexSDK* library product links the 4 shared targets plus the 2
// variant-specific targets for its flavour, so consumers still get
// `import WebexSDK` regardless of which library product they depend on.
//
// WebexBroadcastExtensionKit is a separate product (the SwiftPM equivalent of
// the WebexBroadcastExtensionKit CocoaPod). It only links system frameworks and
// communicates with the host app over a local socket, so it has no dependency
// on the WebexSDK frameworks. Add it to your Broadcast Upload Extension target,
// NOT to your main app target, and `import WebexBroadcastExtensionKit` there.
//
// The dedup is safe only as long as the 4 "Shared" frameworks and the broadcast
// framework remain byte-identical across all 4 variants. build_spm_release.sh
// verifies this invariant at packaging time and refuses to dedup on divergence.

import PackageDescription

let version = "3.17.0"
let base = "https://github.com/balaobulreddy/iOS-spm-test/releases/download/\(version)"

let package = Package(
    name: "WebexSDK",
    platforms: [.iOS(.v15)],
    products: [
        .library(
            name: "WebexSDK",
            targets: [
                "WebexSDK_Full",
                "UCFBridge_Full",
                "util_ios_Shared",
                "wbxaecodec_Shared",
                "wbxaudioengine_Shared",
                "mediastores_ios_Shared",
            ]
        ),
        .library(
            name: "WebexSDKMeeting",
            targets: [
                "WebexSDK_Meeting",
                "UCFBridge_Meeting",
                "util_ios_Shared",
                "wbxaecodec_Shared",
                "wbxaudioengine_Shared",
                "mediastores_ios_Shared",
            ]
        ),
        .library(
            name: "WebexSDKWxc",
            targets: [
                "WebexSDK_Wxc",
                "UCFBridge_Wxc",
                "util_ios_Shared",
                "wbxaecodec_Shared",
                "wbxaudioengine_Shared",
                "mediastores_ios_Shared",
            ]
        ),
        .library(
            name: "WebexSDKMessage",
            targets: [
                "WebexSDK_Message",
                "UCFBridge_Message",
                "util_ios_Shared",
                "wbxaecodec_Shared",
                "wbxaudioengine_Shared",
                "mediastores_ios_Shared",
            ]
        ),
        .library(
            name: "WebexBroadcastExtensionKit",
            targets: [
                "WebexBroadcastExtensionKit",
            ]
        ),
    ],
    targets: [
        // ---------- Shared (one copy, referenced by every variant library) ----------
        .binaryTarget(
            name: "util_ios_Shared",
            url: "\(base)/WebexSDK-Shared-util_ios.xcframework.zip",
            checksum: "89c38d9512ebbea5dbd5e48c7af78b1048b2ef94101f8d0302bf7da711651d8e"
        ),
        .binaryTarget(
            name: "wbxaecodec_Shared",
            url: "\(base)/WebexSDK-Shared-wbxaecodec.xcframework.zip",
            checksum: "526797c7affadc673ba39a024a80a536fad995935db33290935e432a942b8b17"
        ),
        .binaryTarget(
            name: "wbxaudioengine_Shared",
            url: "\(base)/WebexSDK-Shared-wbxaudioengine.xcframework.zip",
            checksum: "19e854600896654d2b2c41984f50279368e2ec09cf0d1f3331725608b6eae92b"
        ),
        .binaryTarget(
            name: "mediastores_ios_Shared",
            url: "\(base)/WebexSDK-Shared-mediastores_ios.xcframework.zip",
            checksum: "639fa485fbd90b7133ff7aa4f62beb92512b1eb8740db362edc95692448047dc"
        ),

        // ---------- Full ----------
        .binaryTarget(
            name: "WebexSDK_Full",
            url: "\(base)/WebexSDK-Full-WebexSDK.xcframework.zip",
            checksum: "b12ec95fe275a2634682b6ef1c9758b60c0ce3833130db103abc14318a20f4ff"
        ),
        .binaryTarget(
            name: "UCFBridge_Full",
            url: "\(base)/WebexSDK-Full-UCFBridge.xcframework.zip",
            checksum: "925a36c7d3c5863d2ae7d5c5418a06f9827fc310fc8e4b3249a057bf3e127c98"
        ),

        // ---------- Meeting ----------
        .binaryTarget(
            name: "WebexSDK_Meeting",
            url: "\(base)/WebexSDK-Meeting-WebexSDK.xcframework.zip",
            checksum: "462b8db8b6a1f459207dbf8059c19903fb2f756765b42fa7369e2bad8544dfa3"
        ),
        .binaryTarget(
            name: "UCFBridge_Meeting",
            url: "\(base)/WebexSDK-Meeting-UCFBridge.xcframework.zip",
            checksum: "72e42fc5e945f53e271d4bb44dd97ada6234256348873b68bbde2d796bfc2aad"
        ),

        // ---------- Wxc ----------
        .binaryTarget(
            name: "WebexSDK_Wxc",
            url: "\(base)/WebexSDK-Wxc-WebexSDK.xcframework.zip",
            checksum: "b49ba34ccf7a288bc00610797d4b6d08085678e41f693aa2f670b3d48e114017"
        ),
        .binaryTarget(
            name: "UCFBridge_Wxc",
            url: "\(base)/WebexSDK-Wxc-UCFBridge.xcframework.zip",
            checksum: "40e10f7b320166cfcb9c8778f3f1b7e762424cdab0baeae81f4933b3fcd49975"
        ),

        // ---------- Message ----------
        .binaryTarget(
            name: "WebexSDK_Message",
            url: "\(base)/WebexSDK-Message-WebexSDK.xcframework.zip",
            checksum: "c482242a84a9310bb31bc2229e6f5ef81e4ff19726cb0b3fc60917087ec0efde"
        ),
        .binaryTarget(
            name: "UCFBridge_Message",
            url: "\(base)/WebexSDK-Message-UCFBridge.xcframework.zip",
            checksum: "34bf7e2809523562a9f1e906346f258c3923631ef2613f05940635d2f06e8063"
        ),

        // ---------- Broadcast (standalone product, shipped once) ----------
        .binaryTarget(
            name: "WebexBroadcastExtensionKit",
            url: "\(base)/WebexBroadcastExtensionKit.xcframework.zip",
            checksum: "e4a6ac3010c4e4dea819870db4d98251983aa8a353cff8661889b181f195fb4a"
        ),
    ]
)
